logging:
  level:
    cn:
      licoy:
        wdog: debug
spring:
  datasource:
    url: jdbc:mysql://nfs-1:32770/wdog?useUnicode=yes&characterEncoding=UTF8&useSSL=false
    username: root
    password: centling
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  redis:
    host: nfs-1
    port: 6379
    password: centling
    timeout: 10000
    pool:
      max-active: 10
      min-idle: 3
      max-idle: 5
  aop:
    proxy-target-class: true
    auto: true
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
  port: 10000